_wandb:
    value:
        cli_version: 0.27.0
        e:
            gf1k7fqs7ot6vkjlsdfjliq1ubcjjylb:
                args:
                    - --layout-names
                    - 3_chefs_counter_circuit
                    - --algo-name
                    - SP
                    - --num-players
                    - "3"
                    - --teammates-len
                    - "2"
                    - --total-ego-agents
                    - "3"
                    - --n-x-sp-total-training-timesteps
                    - "80000000"
                    - --epoch-timesteps
                    - "50000"
                    - --eval-steps-interval
                    - "20"
                    - --n-envs
                    - "20"
                    - --batch-size
                    - "128"
                    - --num-of-ckpoints
                    - "40"
                    - --custom-agent-ck-rate-generation
                    - "4"
                    - --num-steps-in-traj-for-dyn-adv
                    - "2"
                    - --num-static-advs-per-heatmap
                    - "1"
                    - --num-dynamic-advs-per-heatmap
                    - "1"
                    - --use-val-func-for-heatmap-gen
                    - "false"
                    - --prioritized-sampling
                    - "false"
                    - --pop-total-training-timesteps
                    - "80000000"
                    - --fcp-total-training-timesteps
                    - "80000000"
                    - --adversary-total-training-timesteps
                    - "80000000"
                    - --n-x-fcp-total-training-timesteps
                    - "80000000"
                    - --pop-force-training
                    - "false"
                    - --adversary-force-training
                    - "false"
                    - --primary-force-training
                    - "false"
                    - --how-long
                    - "20"
                    - --exp-dir
                    - Classic/3
                    - --wandb-mode
                    - online
                codePath: scripts/train_agents.py
                codePathLocal: scripts/train_agents.py
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "21474836480"
                        used: "2131562496"
                email: sjs020523@gmail.com
                executable: /usr/bin/python
                git:
                    commit: ea915f800a828c4500ed645cabaf9248a821c9be
                    remote: https://github.com/SehunLee0/multiHRI.git
                gpu: NVIDIA RTX A6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-eac3faf9-299b-5fce-f5db-c42e9fc182f0
                host: ca7573c3e89a
                memory:
                    total: "473231945728"
                os: Linux-6.5.0-35-generic-x86_64-with-glibc2.35
                program: /workspace/multiHRI/scripts/train_agents.py
                python: CPython 3.10.12
                root: /workspace/multiHRI/wandb
                startedAt: "2026-05-30T21:07:46.289861Z"
                writerId: gf1k7fqs7ot6vkjlsdfjliq1ubcjjylb
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
            "4": 3.10.12
            "5": 0.27.0
            "10":
                - 20
            "12": 0.27.0
            "13": linux-x86_64
