_wandb:
    value:
        cli_version: 0.27.0
        e:
            i5kz7mw04vddhbxwdybgt1ikoe8wlcsl:
                args:
                    - --layout-names
                    - 3_chefs_counter_circuit
                    - --algo-name
                    - SPN_1ADV
                    - --num-players
                    - "3"
                    - --total-ego-agents
                    - "2"
                    - --teammates-len
                    - "1"
                    - --max-concurrent-jobs
                    - "3"
                    - --n-x-sp-total-training-timesteps
                    - "15000000"
                    - --adversary-total-training-timesteps
                    - "15000000"
                    - --pop-total-training-timesteps
                    - "30000000"
                    - --epoch-timesteps
                    - "50000"
                    - --eval-steps-interval
                    - "20"
                    - --n-envs
                    - "384"
                    - --batch-size
                    - "128"
                    - --num-of-ckpoints
                    - "40"
                    - --custom-agent-ck-rate-generation
                    - "4"
                    - --num-steps-in-traj-for-dyn-adv
                    - "2"
                    - --num-static-advs-per-heatmap
                    - "1"
                    - --num-dynamic-advs-per-heatmap
                    - "1"
                    - --use-val-func-for-heatmap-gen
                    - "false"
                    - --prioritized-sampling
                    - "false"
                    - --pop-force-training
                    - "false"
                    - --adversary-force-training
                    - "false"
                    - --primary-force-training
                    - "false"
                    - --how-long
                    - "20"
                    - --exp-dir
                    - Classic/3
                    - --wandb-mode
                    - online
                codePath: scripts/train_agents.py
                codePathLocal: scripts/train_agents.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "21474836480"
                        used: "2339565568"
                email: sjs020523@gmail.com
                executable: /usr/bin/python
                git:
                    commit: 29fbbfc850225cf8e3b92812faccf8629ca82348
                    remote: https://github.com/jin-seop-shin/multiHRI
                gpu: NVIDIA RTX A4500
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 7168
                      memoryTotal: "21464350720"
                      name: NVIDIA RTX A4500
                      uuid: GPU-d2fca97e-e3f7-fb68-b755-57cf81343b7d
                host: 8d4cf7d51ce7
                memory:
                    total: "270100307968"
                os: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
                program: /workspace/multiHRI/scripts/train_agents.py
                python: CPython 3.11.10
                root: /workspace/multiHRI/wandb
                startedAt: "2026-05-31T20:07:52.455745Z"
                writerId: i5kz7mw04vddhbxwdybgt1ikoe8wlcsl
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
            "4": 3.11.10
            "5": 0.27.0
            "10":
                - 20
            "12": 0.27.0
            "13": linux-x86_64
